before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq mysql-server nginx wget

script: "./travis/run.sh"

after_script:
  # output contents of files w / debugging info to screen
  - cat /var/log/nginx/error.log
